In [ ]:
#!pip -q install transformers datasets evaluate accelerate torch

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\owzya\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

DeepPavlov/rubert-base-cased

In [ ]:
import pandas as pd

data = pd.read_csv("data.csv", sep="\t")
data["sentiment"] = data["sentiment"].replace({"neautral": "neutral"})
data = data.dropna(subset=["review", "sentiment"]).copy()

print(data.shape)
print(data["sentiment"].value_counts())
data.head()

(90000, 2)
sentiment
negative    30000
neutral     30000
positive    30000
Name: count, dtype: int64

                                              review sentiment
0  качество плохое пошив ужасный (горловина напер...  negative
1  Товар отдали другому человеку, я не получила п...  negative
2  Ужасная синтетика! Тонкая, ничего общего с пре...  negative
3  товар не пришел, продавец продлил защиту без м...  negative
4      Кофточка голая синтетика, носить не возможно.  negative

In [ ]:
label2id = {"negative": 0, "neutral": 1, "positive": 2}
id2label = {v: k for k, v in label2id.items()}

data["sentiment"] = data["sentiment"].astype(str).str.strip().str.lower()

unknown = set(data["sentiment"].unique()) - set(label2id.keys())
print("Unknown labels:", unknown)

data["label"] = data["sentiment"].map(label2id)
data[["review", "sentiment", "label"]].head()

Unknown labels: set()

                                              review sentiment  label
0  качество плохое пошив ужасный (горловина напер...  negative      0
1  Товар отдали другому человеку, я не получила п...  negative      0
2  Ужасная синтетика! Тонкая, ничего общего с пре...  negative      0
3  товар не пришел, продавец продлил защиту без м...  negative      0
4      Кофточка голая синтетика, носить не возможно.  negative      0

In [4]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    data[["review", "label"]],
    test_size=0.2,
    random_state=42,
    stratify=data["label"]
)

print(train_df.shape, test_df.shape)

(72000, 2) (18000, 2)

In [5]:
from datasets import Dataset

train_ds = Dataset.from_pandas(train_df.reset_index(drop=True))
test_ds  = Dataset.from_pandas(test_df.reset_index(drop=True))

train_ds, test_ds

(Dataset({
     features: ['review', 'label'],
     num_rows: 72000
 }),
 Dataset({
     features: ['review', 'label'],
     num_rows: 18000
 }))

In [6]:
from transformers import AutoTokenizer

model_name = "DeepPavlov/rubert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

max_len = 192

def tokenize(batch):
    return tokenizer(
        batch["review"],
        truncation=True,
        padding=False,
        max_length=max_len
    )

train_tok = train_ds.map(tokenize, batched=True, remove_columns=["review"])
test_tok  = test_ds.map(tokenize, batched=True, remove_columns=["review"])

train_tok[0]

tokenizer_config.json:   0%|          | 0.00/24.0 [00:00<?, ?B/s]

C:\Users\owzya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\owzya\.cache\huggingface\hub\models--DeepPavlov--rubert-base-cased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config.json:   0%|          | 0.00/642 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Map:   0%|          | 0/72000 [00:00<?, ? examples/s]

Map:   0%|          | 0/18000 [00:00<?, ? examples/s]

{'label': 2,
 'input_ids': [101, 74216, 24991, 8152, 27418, 1515, 68660, 6636, 102],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [7]:
import numpy as np
import evaluate

from transformers import (
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer
)

accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy.compute(predictions=preds, references=labels)["accuracy"],
        "f1_macro": f1.compute(predictions=preds, references=labels, average="macro")["f1"],
    }

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3,
    id2label=id2label,
    label2id=label2id
)

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at DeepPavlov/rubert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [8]:
training_args = TrainingArguments(
    output_dir="rubert_sentiment_runs",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_steps=50,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=test_tok,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

C:\Users\owzya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\owzya\AppData\Local\Temp\ipykernel_3184\3341249942.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [9]:
trainer.train()

  0%|          | 0/9000 [00:00<?, ?it/s]

{'loss': 1.0268, 'grad_norm': 4.50253963470459, 'learning_rate': 1.988888888888889e-05, 'epoch': 0.01}
{'loss': 0.7268, 'grad_norm': 15.228668212890625, 'learning_rate': 1.977777777777778e-05, 'epoch': 0.02}
{'loss': 0.7247, 'grad_norm': 5.896280288696289, 'learning_rate': 1.9666666666666666e-05, 'epoch': 0.03}
{'loss': 0.6743, 'grad_norm': 8.168959617614746, 'learning_rate': 1.9555555555555557e-05, 'epoch': 0.04}
{'loss': 0.67, 'grad_norm': 7.566402912139893, 'learning_rate': 1.9444444444444445e-05, 'epoch': 0.06}
{'loss': 0.6286, 'grad_norm': 22.67428970336914, 'learning_rate': 1.9333333333333333e-05, 'epoch': 0.07}
{'loss': 0.6223, 'grad_norm': 4.908501148223877, 'learning_rate': 1.9222222222222225e-05, 'epoch': 0.08}
{'loss': 0.6543, 'grad_norm': 9.405413627624512, 'learning_rate': 1.9111111111111113e-05, 'epoch': 0.09}
{'loss': 0.6325, 'grad_norm': 6.912664413452148, 'learning_rate': 1.9e-05, 'epoch': 0.1}
{'loss': 0.6374, 'grad_norm': 10.987982749938965, 'learning_rate': 1.888888888888889e-05, 'epoch': 0.11}
{'loss': 0.5887, 'grad_norm': 4.14710807800293, 'learning_rate': 1.877777777777778e-05, 'epoch': 0.12}
{'loss': 0.6066, 'grad_norm': 4.376248359680176, 'learning_rate': 1.866666666666667e-05, 'epoch': 0.13}
{'loss': 0.6048, 'grad_norm': 6.060683250427246, 'learning_rate': 1.8555555555555557e-05, 'epoch': 0.14}
{'loss': 0.6029, 'grad_norm': 7.188655376434326, 'learning_rate': 1.8444444444444448e-05, 'epoch': 0.16}
{'loss': 0.5433, 'grad_norm': 11.013604164123535, 'learning_rate': 1.8333333333333333e-05, 'epoch': 0.17}
{'loss': 0.6004, 'grad_norm': 3.897303819656372, 'learning_rate': 1.8222222222222224e-05, 'epoch': 0.18}
{'loss': 0.5672, 'grad_norm': 10.620943069458008, 'learning_rate': 1.8111111111111112e-05, 'epoch': 0.19}
{'loss': 0.6064, 'grad_norm': 14.502106666564941, 'learning_rate': 1.8e-05, 'epoch': 0.2}
{'loss': 0.5732, 'grad_norm': 17.8358211517334, 'learning_rate': 1.7888888888888892e-05, 'epoch': 0.21}
{'loss': 0.5527, 'grad_norm': 4.8793559074401855, 'learning_rate': 1.7777777777777777e-05, 'epoch': 0.22}
{'loss': 0.5711, 'grad_norm': 7.857763767242432, 'learning_rate': 1.7666666666666668e-05, 'epoch': 0.23}
{'loss': 0.6137, 'grad_norm': 5.578175067901611, 'learning_rate': 1.7555555555555556e-05, 'epoch': 0.24}
{'loss': 0.5769, 'grad_norm': 4.1509175300598145, 'learning_rate': 1.7444444444444448e-05, 'epoch': 0.26}
{'loss': 0.5454, 'grad_norm': 5.210122108459473, 'learning_rate': 1.7333333333333336e-05, 'epoch': 0.27}
{'loss': 0.6385, 'grad_norm': 4.019819736480713, 'learning_rate': 1.7222222222222224e-05, 'epoch': 0.28}
{'loss': 0.5428, 'grad_norm': 8.742632865905762, 'learning_rate': 1.7111111111111112e-05, 'epoch': 0.29}
{'loss': 0.6011, 'grad_norm': 7.040037155151367, 'learning_rate': 1.7e-05, 'epoch': 0.3}
{'loss': 0.5326, 'grad_norm': 15.816248893737793, 'learning_rate': 1.688888888888889e-05, 'epoch': 0.31}
{'loss': 0.5569, 'grad_norm': 4.464812278747559, 'learning_rate': 1.677777777777778e-05, 'epoch': 0.32}
{'loss': 0.5599, 'grad_norm': 5.082782745361328, 'learning_rate': 1.6666666666666667e-05, 'epoch': 0.33}
{'loss': 0.5285, 'grad_norm': 5.979682922363281, 'learning_rate': 1.6555555555555556e-05, 'epoch': 0.34}
{'loss': 0.563, 'grad_norm': 4.353511333465576, 'learning_rate': 1.6444444444444444e-05, 'epoch': 0.36}
{'loss': 0.5635, 'grad_norm': 5.64493465423584, 'learning_rate': 1.6333333333333335e-05, 'epoch': 0.37}
{'loss': 0.5755, 'grad_norm': 5.843451976776123, 'learning_rate': 1.6222222222222223e-05, 'epoch': 0.38}
{'loss': 0.5814, 'grad_norm': 5.994683265686035, 'learning_rate': 1.6111111111111115e-05, 'epoch': 0.39}
{'loss': 0.5531, 'grad_norm': 3.6314823627471924, 'learning_rate': 1.6000000000000003e-05, 'epoch': 0.4}
{'loss': 0.5704, 'grad_norm': 4.355398654937744, 'learning_rate': 1.588888888888889e-05, 'epoch': 0.41}
{'loss': 0.614, 'grad_norm': 4.863742828369141, 'learning_rate': 1.577777777777778e-05, 'epoch': 0.42}
{'loss': 0.5366, 'grad_norm': 14.705991744995117, 'learning_rate': 1.5666666666666667e-05, 'epoch': 0.43}
{'loss': 0.6288, 'grad_norm': 4.956096649169922, 'learning_rate': 1.555555555555556e-05, 'epoch': 0.44}
{'loss': 0.5293, 'grad_norm': 8.54188346862793, 'learning_rate': 1.5444444444444446e-05, 'epoch': 0.46}
{'loss': 0.5588, 'grad_norm': 12.283293724060059, 'learning_rate': 1.5333333333333334e-05, 'epoch': 0.47}
{'loss': 0.5068, 'grad_norm': 9.9539155960083, 'learning_rate': 1.5222222222222223e-05, 'epoch': 0.48}
{'loss': 0.5562, 'grad_norm': 4.036488056182861, 'learning_rate': 1.5111111111111112e-05, 'epoch': 0.49}
{'loss': 0.5676, 'grad_norm': 6.599599361419678, 'learning_rate': 1.5000000000000002e-05, 'epoch': 0.5}
{'loss': 0.5487, 'grad_norm': 5.176940441131592, 'learning_rate': 1.488888888888889e-05, 'epoch': 0.51}
{'loss': 0.5462, 'grad_norm': 2.9111831188201904, 'learning_rate': 1.477777777777778e-05, 'epoch': 0.52}
{'loss': 0.5194, 'grad_norm': 7.538540840148926, 'learning_rate': 1.4666666666666666e-05, 'epoch': 0.53}
{'loss': 0.5209, 'grad_norm': 7.411615371704102, 'learning_rate': 1.4555555555555556e-05, 'epoch': 0.54}
{'loss': 0.512, 'grad_norm': 6.973145008087158, 'learning_rate': 1.4444444444444446e-05, 'epoch': 0.56}
{'loss': 0.5596, 'grad_norm': 8.138901710510254, 'learning_rate': 1.4333333333333334e-05, 'epoch': 0.57}
{'loss': 0.5874, 'grad_norm': 14.556445121765137, 'learning_rate': 1.4222222222222224e-05, 'epoch': 0.58}
{'loss': 0.5873, 'grad_norm': 4.481058120727539, 'learning_rate': 1.4111111111111113e-05, 'epoch': 0.59}
{'loss': 0.5177, 'grad_norm': 7.168507099151611, 'learning_rate': 1.4e-05, 'epoch': 0.6}
{'loss': 0.5418, 'grad_norm': 9.20179271697998, 'learning_rate': 1.388888888888889e-05, 'epoch': 0.61}
{'loss': 0.4922, 'grad_norm': 11.995573043823242, 'learning_rate': 1.377777777777778e-05, 'epoch': 0.62}
{'loss': 0.5351, 'grad_norm': 7.722414016723633, 'learning_rate': 1.3666666666666667e-05, 'epoch': 0.63}
{'loss': 0.5482, 'grad_norm': 3.491652011871338, 'learning_rate': 1.3555555555555557e-05, 'epoch': 0.64}
{'loss': 0.5449, 'grad_norm': 7.258326053619385, 'learning_rate': 1.3444444444444447e-05, 'epoch': 0.66}
{'loss': 0.4886, 'grad_norm': 4.719995021820068, 'learning_rate': 1.3333333333333333e-05, 'epoch': 0.67}
{'loss': 0.5449, 'grad_norm': 8.454045295715332, 'learning_rate': 1.3222222222222223e-05, 'epoch': 0.68}
{'loss': 0.5337, 'grad_norm': 7.572749137878418, 'learning_rate': 1.3111111111111113e-05, 'epoch': 0.69}
{'loss': 0.5175, 'grad_norm': 5.931137561798096, 'learning_rate': 1.3000000000000001e-05, 'epoch': 0.7}
{'loss': 0.5343, 'grad_norm': 6.19224214553833, 'learning_rate': 1.288888888888889e-05, 'epoch': 0.71}
{'loss': 0.5809, 'grad_norm': 6.849845886230469, 'learning_rate': 1.2777777777777777e-05, 'epoch': 0.72}
{'loss': 0.5239, 'grad_norm': 3.992811679840088, 'learning_rate': 1.2666666666666667e-05, 'epoch': 0.73}
{'loss': 0.5125, 'grad_norm': 5.559101104736328, 'learning_rate': 1.2555555555555557e-05, 'epoch': 0.74}
{'loss': 0.4986, 'grad_norm': 10.26235580444336, 'learning_rate': 1.2444444444444446e-05, 'epoch': 0.76}
{'loss': 0.5646, 'grad_norm': 6.3315205574035645, 'learning_rate': 1.2333333333333334e-05, 'epoch': 0.77}
{'loss': 0.5493, 'grad_norm': 16.623992919921875, 'learning_rate': 1.2222222222222224e-05, 'epoch': 0.78}
{'loss': 0.5353, 'grad_norm': 4.964269638061523, 'learning_rate': 1.211111111111111e-05, 'epoch': 0.79}
{'loss': 0.5444, 'grad_norm': 5.125195026397705, 'learning_rate': 1.2e-05, 'epoch': 0.8}
{'loss': 0.561, 'grad_norm': 8.567242622375488, 'learning_rate': 1.188888888888889e-05, 'epoch': 0.81}
{'loss': 0.5419, 'grad_norm': 5.878637313842773, 'learning_rate': 1.177777777777778e-05, 'epoch': 0.82}
{'loss': 0.5129, 'grad_norm': 5.99819278717041, 'learning_rate': 1.1666666666666668e-05, 'epoch': 0.83}
{'loss': 0.5079, 'grad_norm': 4.082569599151611, 'learning_rate': 1.1555555555555556e-05, 'epoch': 0.84}
{'loss': 0.5553, 'grad_norm': 3.9838240146636963, 'learning_rate': 1.1444444444444444e-05, 'epoch': 0.86}
{'loss': 0.5337, 'grad_norm': 3.0122604370117188, 'learning_rate': 1.1333333333333334e-05, 'epoch': 0.87}
{'loss': 0.5441, 'grad_norm': 7.030507564544678, 'learning_rate': 1.1222222222222224e-05, 'epoch': 0.88}
{'loss': 0.5428, 'grad_norm': 24.54663848876953, 'learning_rate': 1.1111111111111113e-05, 'epoch': 0.89}
{'loss': 0.5571, 'grad_norm': 3.498192071914673, 'learning_rate': 1.1000000000000001e-05, 'epoch': 0.9}
{'loss': 0.5148, 'grad_norm': 8.886968612670898, 'learning_rate': 1.088888888888889e-05, 'epoch': 0.91}
{'loss': 0.5363, 'grad_norm': 3.4184436798095703, 'learning_rate': 1.0777777777777778e-05, 'epoch': 0.92}
{'loss': 0.519, 'grad_norm': 6.168618202209473, 'learning_rate': 1.0666666666666667e-05, 'epoch': 0.93}
{'loss': 0.4939, 'grad_norm': 5.474260330200195, 'learning_rate': 1.0555555555555557e-05, 'epoch': 0.94}
{'loss': 0.5108, 'grad_norm': 10.150012016296387, 'learning_rate': 1.0444444444444445e-05, 'epoch': 0.96}
{'loss': 0.5324, 'grad_norm': 5.216211795806885, 'learning_rate': 1.0333333333333335e-05, 'epoch': 0.97}
{'loss': 0.5001, 'grad_norm': 5.734028339385986, 'learning_rate': 1.0222222222222223e-05, 'epoch': 0.98}
{'loss': 0.5314, 'grad_norm': 9.166706085205078, 'learning_rate': 1.0111111111111111e-05, 'epoch': 0.99}
{'loss': 0.5575, 'grad_norm': 8.399970054626465, 'learning_rate': 1e-05, 'epoch': 1.0}

  0%|          | 0/563 [00:00<?, ?it/s]

{'eval_loss': 0.5027967691421509, 'eval_accuracy': 0.7764444444444445, 'eval_f1_macro': 0.7790907489597004, 'eval_runtime': 53.5068, 'eval_samples_per_second': 336.406, 'eval_steps_per_second': 10.522, 'epoch': 1.0}
{'loss': 0.4585, 'grad_norm': 4.1993207931518555, 'learning_rate': 9.88888888888889e-06, 'epoch': 1.01}
{'loss': 0.5067, 'grad_norm': 10.37187385559082, 'learning_rate': 9.777777777777779e-06, 'epoch': 1.02}
{'loss': 0.4658, 'grad_norm': 8.004670143127441, 'learning_rate': 9.666666666666667e-06, 'epoch': 1.03}
{'loss': 0.4363, 'grad_norm': 6.829779624938965, 'learning_rate': 9.555555555555556e-06, 'epoch': 1.04}
{'loss': 0.4716, 'grad_norm': 13.139161109924316, 'learning_rate': 9.444444444444445e-06, 'epoch': 1.06}
{'loss': 0.5095, 'grad_norm': 5.897472858428955, 'learning_rate': 9.333333333333334e-06, 'epoch': 1.07}
{'loss': 0.4617, 'grad_norm': 6.7088470458984375, 'learning_rate': 9.222222222222224e-06, 'epoch': 1.08}
{'loss': 0.4401, 'grad_norm': 9.444256782531738, 'learning_rate': 9.111111111111112e-06, 'epoch': 1.09}
{'loss': 0.4534, 'grad_norm': 8.588691711425781, 'learning_rate': 9e-06, 'epoch': 1.1}
{'loss': 0.4559, 'grad_norm': 3.295535087585449, 'learning_rate': 8.888888888888888e-06, 'epoch': 1.11}
{'loss': 0.4492, 'grad_norm': 9.730801582336426, 'learning_rate': 8.777777777777778e-06, 'epoch': 1.12}
{'loss': 0.4763, 'grad_norm': 6.999594211578369, 'learning_rate': 8.666666666666668e-06, 'epoch': 1.13}
{'loss': 0.4256, 'grad_norm': 9.507586479187012, 'learning_rate': 8.555555555555556e-06, 'epoch': 1.14}
{'loss': 0.4181, 'grad_norm': 5.725486755371094, 'learning_rate': 8.444444444444446e-06, 'epoch': 1.16}
{'loss': 0.4783, 'grad_norm': 4.274821758270264, 'learning_rate': 8.333333333333334e-06, 'epoch': 1.17}
{'loss': 0.4465, 'grad_norm': 5.2624993324279785, 'learning_rate': 8.222222222222222e-06, 'epoch': 1.18}
{'loss': 0.4681, 'grad_norm': 10.513286590576172, 'learning_rate': 8.111111111111112e-06, 'epoch': 1.19}
{'loss': 0.4548, 'grad_norm': 7.815672874450684, 'learning_rate': 8.000000000000001e-06, 'epoch': 1.2}
{'loss': 0.4707, 'grad_norm': 9.48041820526123, 'learning_rate': 7.88888888888889e-06, 'epoch': 1.21}
{'loss': 0.4752, 'grad_norm': 8.583146095275879, 'learning_rate': 7.77777777777778e-06, 'epoch': 1.22}
{'loss': 0.4927, 'grad_norm': 4.063444137573242, 'learning_rate': 7.666666666666667e-06, 'epoch': 1.23}
{'loss': 0.4606, 'grad_norm': 5.826536655426025, 'learning_rate': 7.555555555555556e-06, 'epoch': 1.24}
{'loss': 0.4521, 'grad_norm': 9.637040138244629, 'learning_rate': 7.444444444444445e-06, 'epoch': 1.26}
{'loss': 0.488, 'grad_norm': 33.06519317626953, 'learning_rate': 7.333333333333333e-06, 'epoch': 1.27}
{'loss': 0.4415, 'grad_norm': 11.2000093460083, 'learning_rate': 7.222222222222223e-06, 'epoch': 1.28}
{'loss': 0.4487, 'grad_norm': 10.741100311279297, 'learning_rate': 7.111111111111112e-06, 'epoch': 1.29}
{'loss': 0.4163, 'grad_norm': 8.930991172790527, 'learning_rate': 7e-06, 'epoch': 1.3}
{'loss': 0.4506, 'grad_norm': 6.202250957489014, 'learning_rate': 6.88888888888889e-06, 'epoch': 1.31}
{'loss': 0.4611, 'grad_norm': 4.5633039474487305, 'learning_rate': 6.777777777777779e-06, 'epoch': 1.32}
{'loss': 0.4582, 'grad_norm': 8.92099380493164, 'learning_rate': 6.666666666666667e-06, 'epoch': 1.33}
{'loss': 0.4692, 'grad_norm': 5.640105724334717, 'learning_rate': 6.555555555555556e-06, 'epoch': 1.34}
{'loss': 0.4169, 'grad_norm': 5.26906156539917, 'learning_rate': 6.444444444444445e-06, 'epoch': 1.36}
{'loss': 0.4858, 'grad_norm': 5.730559349060059, 'learning_rate': 6.333333333333333e-06, 'epoch': 1.37}
{'loss': 0.4468, 'grad_norm': 7.408237934112549, 'learning_rate': 6.222222222222223e-06, 'epoch': 1.38}
{'loss': 0.4508, 'grad_norm': 6.624968528747559, 'learning_rate': 6.111111111111112e-06, 'epoch': 1.39}
{'loss': 0.451, 'grad_norm': 6.750705718994141, 'learning_rate': 6e-06, 'epoch': 1.4}
{'loss': 0.4405, 'grad_norm': 8.757952690124512, 'learning_rate': 5.88888888888889e-06, 'epoch': 1.41}
{'loss': 0.447, 'grad_norm': 2.863260507583618, 'learning_rate': 5.777777777777778e-06, 'epoch': 1.42}
{'loss': 0.4273, 'grad_norm': 10.487100601196289, 'learning_rate': 5.666666666666667e-06, 'epoch': 1.43}
{'loss': 0.4692, 'grad_norm': 8.240736961364746, 'learning_rate': 5.555555555555557e-06, 'epoch': 1.44}
{'loss': 0.4959, 'grad_norm': 11.570319175720215, 'learning_rate': 5.444444444444445e-06, 'epoch': 1.46}
{'loss': 0.4451, 'grad_norm': 2.828742265701294, 'learning_rate': 5.333333333333334e-06, 'epoch': 1.47}
{'loss': 0.4804, 'grad_norm': 6.115273952484131, 'learning_rate': 5.2222222222222226e-06, 'epoch': 1.48}
{'loss': 0.4637, 'grad_norm': 10.131919860839844, 'learning_rate': 5.1111111111111115e-06, 'epoch': 1.49}
{'loss': 0.5068, 'grad_norm': 8.334939956665039, 'learning_rate': 5e-06, 'epoch': 1.5}
{'loss': 0.4675, 'grad_norm': 8.432784080505371, 'learning_rate': 4.888888888888889e-06, 'epoch': 1.51}
{'loss': 0.4389, 'grad_norm': 5.719379425048828, 'learning_rate': 4.777777777777778e-06, 'epoch': 1.52}
{'loss': 0.443, 'grad_norm': 6.815028667449951, 'learning_rate': 4.666666666666667e-06, 'epoch': 1.53}
{'loss': 0.4586, 'grad_norm': 8.637251853942871, 'learning_rate': 4.555555555555556e-06, 'epoch': 1.54}
{'loss': 0.4747, 'grad_norm': 11.12640380859375, 'learning_rate': 4.444444444444444e-06, 'epoch': 1.56}
{'loss': 0.4553, 'grad_norm': 10.36584186553955, 'learning_rate': 4.333333333333334e-06, 'epoch': 1.57}
{'loss': 0.4126, 'grad_norm': 6.142733097076416, 'learning_rate': 4.222222222222223e-06, 'epoch': 1.58}
{'loss': 0.4179, 'grad_norm': 9.885262489318848, 'learning_rate': 4.111111111111111e-06, 'epoch': 1.59}
{'loss': 0.4538, 'grad_norm': 19.660371780395508, 'learning_rate': 4.000000000000001e-06, 'epoch': 1.6}
{'loss': 0.4708, 'grad_norm': 10.195633888244629, 'learning_rate': 3.88888888888889e-06, 'epoch': 1.61}
{'loss': 0.4778, 'grad_norm': 12.907477378845215, 'learning_rate': 3.777777777777778e-06, 'epoch': 1.62}
{'loss': 0.4471, 'grad_norm': 7.010123252868652, 'learning_rate': 3.6666666666666666e-06, 'epoch': 1.63}
{'loss': 0.4353, 'grad_norm': 10.350314140319824, 'learning_rate': 3.555555555555556e-06, 'epoch': 1.64}
{'loss': 0.4148, 'grad_norm': 12.776365280151367, 'learning_rate': 3.444444444444445e-06, 'epoch': 1.66}
{'loss': 0.4449, 'grad_norm': 7.7296342849731445, 'learning_rate': 3.3333333333333333e-06, 'epoch': 1.67}
{'loss': 0.4025, 'grad_norm': 10.120430946350098, 'learning_rate': 3.2222222222222227e-06, 'epoch': 1.68}
{'loss': 0.4168, 'grad_norm': 4.242028713226318, 'learning_rate': 3.1111111111111116e-06, 'epoch': 1.69}
{'loss': 0.5232, 'grad_norm': 3.8349382877349854, 'learning_rate': 3e-06, 'epoch': 1.7}
{'loss': 0.4275, 'grad_norm': 6.926653861999512, 'learning_rate': 2.888888888888889e-06, 'epoch': 1.71}
{'loss': 0.4514, 'grad_norm': 10.148771286010742, 'learning_rate': 2.7777777777777783e-06, 'epoch': 1.72}
{'loss': 0.4686, 'grad_norm': 7.666079044342041, 'learning_rate': 2.666666666666667e-06, 'epoch': 1.73}
{'loss': 0.4601, 'grad_norm': 6.100510120391846, 'learning_rate': 2.5555555555555557e-06, 'epoch': 1.74}
{'loss': 0.4795, 'grad_norm': 6.999808311462402, 'learning_rate': 2.4444444444444447e-06, 'epoch': 1.76}
{'loss': 0.5027, 'grad_norm': 4.748885154724121, 'learning_rate': 2.3333333333333336e-06, 'epoch': 1.77}
{'loss': 0.4646, 'grad_norm': 9.497015953063965, 'learning_rate': 2.222222222222222e-06, 'epoch': 1.78}
{'loss': 0.4436, 'grad_norm': 8.86060619354248, 'learning_rate': 2.1111111111111114e-06, 'epoch': 1.79}
{'loss': 0.3998, 'grad_norm': 13.3695650100708, 'learning_rate': 2.0000000000000003e-06, 'epoch': 1.8}
{'loss': 0.4337, 'grad_norm': 14.419164657592773, 'learning_rate': 1.888888888888889e-06, 'epoch': 1.81}
{'loss': 0.4659, 'grad_norm': 8.87878704071045, 'learning_rate': 1.777777777777778e-06, 'epoch': 1.82}
{'loss': 0.4112, 'grad_norm': 12.159744262695312, 'learning_rate': 1.6666666666666667e-06, 'epoch': 1.83}
{'loss': 0.4183, 'grad_norm': 6.578500270843506, 'learning_rate': 1.5555555555555558e-06, 'epoch': 1.84}
{'loss': 0.4525, 'grad_norm': 11.001225471496582, 'learning_rate': 1.4444444444444445e-06, 'epoch': 1.86}
{'loss': 0.4152, 'grad_norm': 11.369661331176758, 'learning_rate': 1.3333333333333334e-06, 'epoch': 1.87}
{'loss': 0.4557, 'grad_norm': 10.11732006072998, 'learning_rate': 1.2222222222222223e-06, 'epoch': 1.88}
{'loss': 0.4607, 'grad_norm': 4.5761799812316895, 'learning_rate': 1.111111111111111e-06, 'epoch': 1.89}
{'loss': 0.4291, 'grad_norm': 7.652820110321045, 'learning_rate': 1.0000000000000002e-06, 'epoch': 1.9}
{'loss': 0.4424, 'grad_norm': 6.6496968269348145, 'learning_rate': 8.88888888888889e-07, 'epoch': 1.91}
{'loss': 0.4543, 'grad_norm': 7.721407413482666, 'learning_rate': 7.777777777777779e-07, 'epoch': 1.92}
{'loss': 0.4742, 'grad_norm': 7.223743915557861, 'learning_rate': 6.666666666666667e-07, 'epoch': 1.93}
{'loss': 0.4086, 'grad_norm': 8.84426498413086, 'learning_rate': 5.555555555555555e-07, 'epoch': 1.94}
{'loss': 0.4342, 'grad_norm': 3.539635419845581, 'learning_rate': 4.444444444444445e-07, 'epoch': 1.96}
{'loss': 0.4516, 'grad_norm': 8.620423316955566, 'learning_rate': 3.3333333333333335e-07, 'epoch': 1.97}
{'loss': 0.4202, 'grad_norm': 4.8127875328063965, 'learning_rate': 2.2222222222222224e-07, 'epoch': 1.98}
{'loss': 0.4202, 'grad_norm': 6.7190656661987305, 'learning_rate': 1.1111111111111112e-07, 'epoch': 1.99}
{'loss': 0.4178, 'grad_norm': 8.032413482666016, 'learning_rate': 0.0, 'epoch': 2.0}

  0%|          | 0/563 [00:00<?, ?it/s]

{'eval_loss': 0.504026472568512, 'eval_accuracy': 0.783, 'eval_f1_macro': 0.7856517694675414, 'eval_runtime': 61.5748, 'eval_samples_per_second': 292.327, 'eval_steps_per_second': 9.143, 'epoch': 2.0}
{'train_runtime': 1733.205, 'train_samples_per_second': 83.083, 'train_steps_per_second': 5.193, 'train_loss': 0.5098138565487332, 'epoch': 2.0}

TrainOutput(global_step=9000, training_loss=0.5098138565487332, metrics={'train_runtime': 1733.205, 'train_samples_per_second': 83.083, 'train_steps_per_second': 5.193, 'total_flos': 7899832365985728.0, 'train_loss': 0.5098138565487332, 'epoch': 2.0})

In [10]:
metrics = trainer.evaluate()
metrics

  0%|          | 0/563 [00:00<?, ?it/s]

{'eval_loss': 0.504026472568512,
 'eval_accuracy': 0.783,
 'eval_f1_macro': 0.7856517694675414,
 'eval_runtime': 55.7022,
 'eval_samples_per_second': 323.147,
 'eval_steps_per_second': 10.107,
 'epoch': 2.0}

In [11]:
from sklearn.metrics import classification_report

pred = trainer.predict(test_tok)
y_true = pred.label_ids
y_pred = np.argmax(pred.predictions, axis=-1)

print(classification_report(y_true, y_pred, target_names=[id2label[0], id2label[1], id2label[2]]))

  0%|          | 0/563 [00:00<?, ?it/s]

              precision    recall  f1-score   support

    negative       0.78      0.72      0.75      6000
     neutral       0.66      0.75      0.70      6000
    positive       0.93      0.87      0.90      6000

    accuracy                           0.78     18000
   macro avg       0.79      0.78      0.79     18000
weighted avg       0.79      0.78      0.79     18000

In [12]:
save_dir = "rubert_sentiment_model"

trainer.save_model(save_dir)
tokenizer.save_pretrained(save_dir)

print("Saved to:", save_dir)

Saved to: rubert_sentiment_model

In [14]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model.to(device)

def predict_rubert(text):

    model.eval()

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=max_len
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        out = model(**inputs)

    cls = int(torch.argmax(out.logits, dim=-1).item())

    return id2label[cls]

In [16]:
predict_rubert("Хорошее качество, рекомендую!")

'positive'

In [25]:
predict_rubert("Качество ужасное, одежда плохая и рвется")

'negative'

In [30]:
predict_rubert("Качество так себе")

'neutral'

In [31]:
import random

for i in range(10):
    
    text = random.choice(test_df["review"].tolist())
    
    pred = predict_rubert(text)
    
    print("Текст:", text[:120])
    print("Предсказание:", pred)
    print()

Текст: На 42 S подошёл идеально. Цена соответствует качеству!
Предсказание: positive

Текст: товар после таможни не отслеживался на почту так и не пришол.После срока защиты покупателя оплату провели спор пропал. в
Предсказание: negative

Текст: максимальный размер:44! ткань в рубчик,смотрится не так как на фото... расстроена,очень на фото оно мне понравилось....(
Предсказание: neutral

Текст: очень долгая доставка  и не отслеживалась
Предсказание: neutral

Текст: Товар не советую, чулки маленькие, резинок нет, а значит их носить нельзя, очень тонкие, порвутся как только будите одев
Предсказание: negative

Текст: отличная кофточка,лёгкая,тонкая!точно как на картинке!размерная сетка соответствует.
Предсказание: positive

Текст: Заказ не пришёл, продавец неохотно вернул деньги
Предсказание: negative

Текст: Имеются дырки на швах, и не маленькие
Предсказание: neutral

Текст: Товар пришёл не тот который заказывала, заказала чёрный с, пришёл красный  другого размера, да ещё и дырявый
Предсказание: negative

Текст: Маломерки, меньше размера на 3. Учтите это при заказе. Материал приятный к телу.
Предсказание: neutral